name: birdy
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  google_fonts: ^2.2.0
  flutter_svg: ^1.0.3
  flutter_screenutil: ^5.1.1
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.3.1
  image_picker: ^0.8.4+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/ml/
    - assets/google_fonts/
